apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hnv-be-adm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true, SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sonntHT1004/argocd-demo-hmm'
    path: hnv-be-common
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hnv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

