apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hnv-be-adm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true, SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: hnv
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev
    repoURL: 'https://github.com/vvnst/hnv-be-adm.git'
    targetRevision: master
      
  sources: []
  project: hnv 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
