apiVersion: apps/v1
kind: Rollout
metadata:
  name: test
  namespace: hnv
  labels:
    app: test
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    canary:
      steps:
      - setWeight: 100
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: "ubuntu:latest"
        args: ["sleep", "3600"]
        envFrom:
        - configMapRef:
            name: test-config
