apiVersion: v1
kind: Pod
metadata:
  name: hnv-be-test
  namespace: default
  labels:
    app: hnv-be-test
spec:
  containers:
  - name: hnv-be-test
    image: "932531822723.dkr.ecr.ap-northeast-2.amazonaws.com/hnv-be-test:0.0.1"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http